import type { Message } from "discord.js";

import type { LinkRecord } from "../db/repository.js";
import type { Logger } from "../logger.js";
import { extractUrls, isYouTubeUrl, extractYouTubeVideoId } from "./url.js";
import type { ContentExtractor } from "./extractor.js";
import { YouTubeApiClient, type YouTubeVideoMetadata } from "./youtube.js";

export interface LinkStore {
  upsertLink(link: LinkRecord): Promise<unknown>;
}

export interface IngestionServiceOptions {
  repository: LinkStore;
  extractor: ContentExtractor;
  summarizer: {
    summarize(content: string): Promise<string>;
  };
  embedder: {
    embed(text: string): Promise<number[]>;
  };
  logger: Logger;
  successReaction: string;
  failureReaction: string;
  youtubeClient?: YouTubeApiClient;
}

export class IngestionService {
  constructor(private readonly options: IngestionServiceOptions) {}

  async ingestMessage(message: Message): Promise<void> {
    const urls = extractUrls(message.content);
    if (!urls.length) {
      return;
    }

    for (const url of urls) {
      try {
        // Check if this is a YouTube URL
        if (isYouTubeUrl(url) && this.options.youtubeClient?.isConfigured()) {
          await this.ingestYouTubeUrl(url, message);
        } else {
          await this.ingestGenericUrl(url, message);
        }
      } catch (error) {
        this.options.logger.warn("Failed to ingest URL", {
          url,
          messageId: message.id,
          error: error instanceof Error ? error.message : String(error)
        });

        await message.react(this.options.failureReaction);
      }
    }
  }

  private async ingestYouTubeUrl(url: string, message: Message): Promise<void> {
    const videoId = extractYouTubeVideoId(url);
    if (!videoId) {
      this.options.logger.warn("Failed to extract YouTube video ID", { url });
      await this.ingestGenericUrl(url, message);
      return;
    }

    this.options.logger.info("Processing YouTube URL", { url, videoId });

    // Fetch metadata from YouTube API
    const metadata = await this.options.youtubeClient!.fetchVideoMetadata(videoId);

    if (!metadata) {
      this.options.logger.warn("Failed to fetch YouTube metadata, falling back to generic extraction", { url, videoId });
      await this.ingestGenericUrl(url, message);
      return;
    }

    // Fetch captions if available
    const captionsResult = await this.options.youtubeClient!.fetchCaptions(videoId);
    const transcript = captionsResult?.transcript ?? null;

    // Generate summary using transcript if available, otherwise use metadata
    let content: string;
    if (transcript) {
      content = [metadata.title, transcript].filter(Boolean).join("\n\n").trim();
      this.options.logger.info("Using transcript for YouTube summary", { 
        url, 
        videoId, 
        transcriptLength: transcript.length,
        language: captionsResult?.language 
      });
    } else {
      content = [metadata.title, metadata.description].filter(Boolean).join("\n\n").trim();
    }
    
    const summary = content ? await this.options.summarizer.summarize(content) : null;
    
    // Generate embedding from best available content
    const embeddingText = transcript 
      ? [metadata.title, transcript].filter(Boolean).join("\n\n").trim()
      : [metadata.title, summary, metadata.description].filter(Boolean).join("\n\n").trim();
    const embedding = embeddingText ? await this.options.embedder.embed(embeddingText) : null;

    await this.options.repository.upsertLink({
      url,
      title: metadata.title,
      summary,
      content: metadata.description,
      transcript,
      imageUrl: metadata.thumbnailUrl,
      embedding,
      metadata: {
        discordMessageId: message.id,
        discordChannelId: message.channelId,
        discordAuthorId: message.author.id,
        contentType: "youtube",
        videoId: metadata.videoId,
        channelTitle: metadata.channelTitle,
        publishedAt: metadata.publishedAt,
        hasTranscript: !!transcript,
        transcriptLanguage: captionsResult?.language ?? null,
        transcriptIsAutoGenerated: captionsResult?.isAutoGenerated ?? null
      }
    });

    this.options.logger.info("Ingested YouTube URL", {
      url,
      videoId,
      title: metadata.title,
      messageId: message.id
    });

    await message.react(this.options.successReaction);
  }

  private async ingestGenericUrl(url: string, message: Message): Promise<void> {
    const extracted = await this.options.extractor.extract(url);
    if (!extracted) {
      throw new Error("No extractable article content returned");
    }

    const baseTextForLlm = [extracted.title, extracted.content].filter(Boolean).join("\n\n").trim();
    const summary = baseTextForLlm ? await this.options.summarizer.summarize(baseTextForLlm) : null;
    const embeddingText = [extracted.title, summary, extracted.content].filter(Boolean).join("\n\n").trim();
    const embedding = embeddingText ? await this.options.embedder.embed(embeddingText) : null;

    await this.options.repository.upsertLink({
      url,
      title: extracted.title,
      summary,
      content: extracted.content,
      imageUrl: extracted.imageUrl,
      embedding,
      metadata: {
        ...extracted.metadata,
        discordMessageId: message.id,
        discordChannelId: message.channelId,
        discordAuthorId: message.author.id
      }
    });

    this.options.logger.info("Ingested URL from message", {
      url,
      messageId: message.id
    });

    await message.react(this.options.successReaction);
  }
}
